### PR TITLE
Fix overlay Entities is not a constructor

### PR DESCRIPTION
**Pull request by MariaAga**
to test:
```
npm install
npm run prepublish 
cd examples/cli/overlay
npm run webpack-dev-server -- --open 
```
uncomment  the lines in `examples/cli/overlay/app.js`
if you see an error in the page and not only in the console it means its working

### CODE REVIEW

**Comment by jeremylenz** [comment]
I see this (no console error, but connection refused error on the page.) Does that mean it's working?

conn_refused

**Comment by jeremylenz** [comment]
I couldn't get `--open` to work because I ran it on my VM

**Comment by MariaAga** [comment]
Nope ):
Screenshot from 2022-04-21 16-03-30

**Comment by adamruzicka** [comment]
What's the status here?

**Comment by MariaAga** [comment]
Waiting to be review and merged @Ron-Lavi

**Comment by adamruzicka** [comment]
ping @Ron-Lavi

**Review by Ron-Lavi — APPROVED** [review]
Thanks @MariaAga !!
This one waited for too long, tested also via npm link and it solved the console warning.

**Pull request merged**
